O módulo assert fornece um conjunto de funções de asserção para verificar invariantes. A função assert.rejects() aguarda a promessa asyncFn ou, se asyncFn for uma função, ela é chamada imediatamente e a promessa retornada é aguardada até sua conclusão. Em seguida, verifica se a promessa foi rejeitada.
Sintaxe:
```
assert.rejects(asyncFn[, error][, message])
```

Parâmetros: Esta função aceita os seguintes parâmetros, conforme mencionado acima e descrito abaixo:
asyncFn: Este parâmetro é uma função assíncrona que gera um erro de forma síncrona.
erro: Esse parâmetro pode ser do tipo Class ou uma expressão Regular ou uma função de validação ou um objeto em que cada propriedade será testada. É um parâmetro opcional.
Mensagem: Esse parâmetro será a mensagem fornecida pelo AssertionError se o asyncFn não for rejeitado. É um parâmetro opcional.

Valor Retornado: Essa função retorna o erro de asserção do tipo de objeto. Instalação do módulo assert:

Você pode acessar o link para instalar o módulo assert. É possível instalar este pacote utilizando o seguinte comando: 
```
npm install assert
```
Observação: A instalação é opcional, pois o módulo já vem embutido no Node.js..

```
Após instalar o módulo assert, você pode verificar sua versão no prompt de comando com: npm version assert
```

Depois disso, basta criar uma pasta e adicionar um arquivo — por exemplo, index.js — como mostrado abaixo.

### Exemplo 1: Nome do arquivo: index.js

```node
// Requiring the module
 const assert = require('assert').strict;

// Function call
(async () => {
    assert.strictEqual(1,2)
    await assert.rejects(
      async () => {
        throw new TypeError('Wrong value');
      },
      (err) => {
        assert.strictEqual(err.name, 'TypeError');
        assert.strictEqual(err.message, 'Wrong value');
        return true;
      }
    ).then(() => {
        console.log("Reject Demo")
    });
})();
```

Etapas para executar o programa:
A estrutura do projeto ficará assim:
  
![](https://media.geeksforgeeks.org/wp-content/uploads/20200606171437/structure56.png)

Execute index.js arquivo usando o comando abaixo:
```
node index.js
```

Saída:
```
(node:12704) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: Expected 
values to be strictly equal:

1 !== 2

    at C:\Users\Lenovo\Downloads\Geeksforgeeks Internship\index.js:25:12
    at Object. (C:\Users\Lenovo\Downloads\Geeksforgeeks Internship\NEW\Assert Function
\index.js:38:3)    
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
(node:12704) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This 
error originated either by throwing inside of an async function without a catch block,
or by rejecting a promise which was not handled with .catch(). To terminate the node
process on unhandled promise rejection,  use the CLI flag `--unhandled-rejections=strict` 
(see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). 
(rejection id: 1)
```

### Exemplo 2: Nome do arquivo: index.js

```node
// Requiring the module
 const assert = require('assert').strict;

// Function call
(async () => {
    assert.strictEqual(1,1)
    await assert.rejects(
      async () => {
        throw new TypeError('Wrong value');
      },
      (err) => {
        assert.strictEqual(err.name, 'TypeError');
        assert.strictEqual(err.message, 'Wrong value');
        return true;
      }
    ).then(() => {
        console.log("Reject Demo Works Successfully")
    });
})();
```

Etapas para executar o programa:
A estrutura do projeto ficará assim.
  
![](https://media.geeksforgeeks.org/wp-content/uploads/20200606171437/structure56.png)

Execute index.js arquivo usando o comando abaixo:
```
node index.js
```

Saída:
```
Reject Demo Works Successfully
```

Reference: https://nodejs.org/dist/latest-v12.x/docs/api/assert.html#assert_assert_rejects_asyncfn_error_message
